services:
    frontend:
        container_name: react_frontend
        build:
            context: ./frontend
        ports:
            - 8080:5173
        depends_on:
            - backend
        volumes:
            - ./frontend:/app
        command: sh -c "npm i && npm run host"

    backend:
        container_name: node_backend
        build:
            context: ./backend
        volumes:
            - ./backend:/backend
        depends_on:
            - db
        ports:
            - 3000:3000
        command: sh -c "npm i && npm run dev"

    db:
        image: postgres
        container_name: postgres_db
        environment:
            POSTGRES_DB: tasks-database
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 1234
        ports:
            - "5432:5432"
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
